version: '3.8'

services:
    simple-web-service:
        image: devopsdockeruh/simple-web-service
        ports:
          - 8000:8080

        command: server
        container_name: simple-web-server
